CREATE TABLE users (
    id          CHAR(36)     NOT NULL PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NULL,
    phone_number VARCHAR(255) NULL UNIQUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
